<?php

namespace backend\modules\user\controllers\actions\temp_user;


class BindExistingUser extends BaseTempUserAction
{


    public function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
    }
}