<?php


namespace common\widgets;


use common\modules\user\models\Nationality;
use yii\base\Widget;

class NationalityInputWidget extends Widget
{

    public $userType;
    public $disabledField = true;
    public $nationalityId = 0;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run();

        Nationality::findOne();

    }

}